import fs from "node:fs";
import path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CommandDispatcher } from "../../bridge/dispatcher.js";
import type { BridgeState } from "../../bridge/state.js";
import { getAllowedRoots, resolveProjectRoot, validateDirectoryPath, validateExportPngPath } from "../../security/fileAccess.js";
import { resolveAnimationPlayback, type AnimationInspection } from "../animationSelection.js";
import { bridgeToolError } from "./common.js";

type EventMarker = { frameNumber: number; name: string; payload?: string };
type Slice = { name: string; bounds: { x: number; y: number; width: number; height: number }; pivot?: { x: number; y: number } | null };

function fileStem(value: string): string {
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/.test(value)) throw new Error("baseName must contain only letters, digits, dots, dashes, and underscores.");
  return value;
}

function godotString(value: string): string {
  return JSON.stringify(value).replace(/^"|"$/g, "");
}

function godotSpriteFrames(
  inspection: AnimationInspection,
  texturePath: string,
  columns: number,
  spacing: number,
  pivot: { x: number; y: number } | null
): string {
  const subresources = inspection.frames.map((frame, index) => {
    const x = (index % columns) * (inspection.width + spacing);
    const y = Math.floor(index / columns) * (inspection.height + spacing);
    return `[sub_resource type="AtlasTexture" id="AtlasTexture_${frame.frameNumber}"]\natlas = ExtResource("1_texture")\nregion = Rect2(${x}, ${y}, ${inspection.width}, ${inspection.height})`;
  });
  const names = inspection.tags.length ? inspection.tags : [{ name: "default", from: 1, to: inspection.frames.length, direction: "forward" as const, repeats: 0 }];
  const animations = names.map((tag) => {
    const playback = resolveAnimationPlayback(inspection, { tagName: inspection.tags.length ? tag.name : undefined });
    const frames = playback.frames.map((frame) => `{
"duration": ${Math.max(0.001, frame.durationMs / 1000)},
"texture": SubResource("AtlasTexture_${frame.frameNumber}")
}`).join(", ");
    const loop = playback.loopsContinuously ? "true" : "false";
    return `{
"frames": [${frames}],
"loop": ${loop},
"name": &"${godotString(tag.name)}",
"speed": 1.0
}`;
  });
  const pivotComment = pivot ? `; Pivot/origin from Aseprite slice: (${pivot.x}, ${pivot.y})\n` : "; No Aseprite pivot slice was selected.\n";
  return `; Generated by aseprite-mcp. Frame durations use speed 1.0 and relative seconds.\n${pivotComment}[gd_resource type="SpriteFrames" load_steps=${inspection.frames.length + 2} format=3]\n\n[ext_resource type="Texture2D" path="${godotString(texturePath)}" id="1_texture"]\n\n${subresources.join("\n\n")}\n\n[resource]\nanimations = [${animations.join(", ")}]\n`;
}

export function registerEngineExportTools(server: McpServer, dispatcher: CommandDispatcher, state: BridgeState): void {
  server.tool(
    "export_engine_assets",
    "Exports one spritesheet plus Godot SpriteFrames and Unity-native import metadata. Tags, per-frame durations, an Aseprite slice pivot, and declared event markers are preserved.",
    {
      outputDirectory: z.string().min(1),
      baseName: z.string().min(1).max(120),
      columns: z.number().int().min(1).max(128).optional(),
      spacing: z.number().int().min(0).max(64).default(0),
      scale: z.number().int().min(1).max(8).default(1),
      pivotSliceName: z.string().min(1).max(128).optional(),
      godotTexturePath: z.string().min(1).max(512).optional().describe("res:// path used by the generated .tres; default assumes the PNG is at the Godot project root"),
      events: z.array(z.object({ frameNumber: z.number().int().positive(), name: z.string().min(1).max(128), payload: z.string().max(1024).optional() }).strict()).max(256).default([]),
      overwrite: z.boolean().default(false),
    },
    async (args) => {
      try {
        const roots = getAllowedRoots();
        const projectRoot = resolveProjectRoot(undefined, roots);
        const outputDirectory = validateDirectoryPath(args.outputDirectory, roots, true, projectRoot);
        const baseName = fileStem(args.baseName);
        const inspection = await dispatcher.send<AnimationInspection>("inspect_animation", {}, 10_000);
        if (typeof inspection.revision === "number") state.setRevision(inspection.revision);
        if (!inspection.frames.length) throw new Error("The active sprite has no frames.");
        for (const event of args.events) {
          if (!inspection.frames.some((frame) => frame.frameNumber === event.frameNumber)) throw new Error(`Event '${event.name}' targets missing frame ${event.frameNumber}.`);
        }
        const slicesResult = await dispatcher.send<{ slices?: Slice[] }>("list_slices", {}, 10_000);
        const slices = slicesResult.slices ?? [];
        const requestedPivot = args.pivotSliceName
          ? slices.find((slice) => slice.name === args.pivotSliceName)
          : slices.find((slice) => slice.name.toLowerCase() === "pivot");
        if (args.pivotSliceName && !requestedPivot) throw new Error(`Pivot slice '${args.pivotSliceName}' was not found.`);
        const pivot = requestedPivot?.pivot
          ? { x: requestedPivot.bounds.x + requestedPivot.pivot.x, y: requestedPivot.bounds.y + requestedPivot.pivot.y }
          : null;
        const columns = Math.min(args.columns ?? inspection.frames.length, inspection.frames.length);
        const pngPath = validateExportPngPath(path.join(outputDirectory, `${baseName}_spritesheet.png`), args.overwrite, roots, true, projectRoot);
        const godotPath = path.join(outputDirectory, `${baseName}.tres`);
        const metadataPath = path.join(outputDirectory, `${baseName}.engine.json`);
        for (const target of [godotPath, metadataPath]) {
          if (!args.overwrite && fs.existsSync(target)) throw new Error(`Refusing to overwrite existing file: ${target}`);
        }
        const exported = await dispatcher.send<any>("export_sprite_sheet", {
          outputPath: pngPath,
          frameNumbers: inspection.frames.map((frame) => frame.frameNumber),
          layout: "grid",
          columns,
          spacing: args.spacing,
          scale: args.scale,
          overwrite: args.overwrite,
        }, 30_000);
        const metadata = {
          formatVersion: 1,
          source: { width: inspection.width, height: inspection.height, revision: inspection.revision ?? state.getRevision() },
          spritesheet: { path: pngPath, columns, spacing: args.spacing, scale: args.scale, frameWidth: inspection.width * args.scale, frameHeight: inspection.height * args.scale },
          pivot,
          tags: inspection.tags.map((tag) => ({ ...tag, playback: resolveAnimationPlayback(inspection, { tagName: tag.name }) })),
          frames: inspection.frames,
          events: args.events as EventMarker[],
          godot: { spriteFramesPath: godotPath, texturePath: args.godotTexturePath ?? `res://${path.basename(pngPath)}`, pivot },
          unity: {
            importMode: "AsepriteImporter",
            sourceAsepriteRequired: true,
            animationClipsFromTags: true,
            preserveFrameTiming: true,
            customPivotNormalized: pivot ? { x: pivot.x / inspection.width, y: pivot.y / inspection.height } : null,
            events: args.events,
            fallbackSpritesheet: { path: pngPath, columns, frameWidth: inspection.width * args.scale, frameHeight: inspection.height * args.scale },
          },
        };
        await fs.promises.writeFile(godotPath, godotSpriteFrames(inspection, metadata.godot.texturePath, columns, args.spacing, pivot), "utf8");
        await fs.promises.writeFile(metadataPath, JSON.stringify(metadata, null, 2), "utf8");
        return { content: [{ type: "text", text: JSON.stringify({ success: true, pngPath, godotPath, metadataPath, frames: inspection.frames.length, tags: inspection.tags.map((tag) => tag.name), pivot, events: args.events, bridgeResult: exported }, null, 2) }] };
      } catch (error) {
        return bridgeToolError(error);
      }
    }
  );
}
